version: "3.8"

services:
  nextjs-app:
    container_name: nextjs_dev_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app
    environment:
      - NODE_ENV=development
